- hosts: processors
  user: ec2-user
  sudo: yes
  gather_facts: no
  vars:
    daemons:
      - consul
      - uwsgi
    packages:
      - app-admin/consul
      - dev-go/go-crypto
      - dev-python/beanstalkc
      - dev-python/consulate
      - dev-python/requests-unixsocket
      - www-servers/nginx
      - www-servers/uwsgi
    portage_use_flags:
      - nginx
      - uwsgi
  roles:
    - common_system
    - app_stack
  tasks:
    - name: consul | copy watcher handler
      template: src=templates/call_api_watch_handler.py dest=/etc/consul.d/call_api_watch_handler.py mode=750 owner=consul
      tags:
        - consul

    - name: consul | configure watches
      copy: src=files/watches.json dest=/etc/consul.d/watches.json
      notify:
        - restart consul
      tags:
        - consul

    - name: code | deploy ep2015_processor sources
      synchronize: src=../ep2015_processor dest=/usr/lib/ recursive=yes copy_links=yes delete=yes
      tags:
        - uwsgi

    - name: uwsgi | copy ep2015_processor ini
      copy: src=files/ep2015_processor.ini dest=/etc/uwsgi.d/ep2015_processor.ini
      tags:
        - uwsgi

    - name: daemons | start and enable at boot
      service: name={{ item }} state=started enabled=yes
      with_items: daemons
      tags:
        - consul
        - uwsgi
